/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -O3 -fno-strict-aliasing  -I/usr/share/nim -o /home/kavis/Documents/Project/ETC/New_Music/nimcache/stdlib_os.o /home/kavis/Documents/Project/ETC/New_Music/nimcache/stdlib_os.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/stat.h>
#include <sys/types.h>
#include <time.h>
#include <string.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef long tyArray_QS4edQct6fXoghbs69aZ9a8w[3];
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_6e5MGL10HDAJ205lBYpWxw)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosaddFileExt)(NimStringDesc* filename, NimStringDesc* ext);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getEnv_9b1nh9cAHhSLlHOPz8lCk5FA)(NimStringDesc* key, NimStringDesc* default_0);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, expandTilde_DOCYVvghSr9cSjyIq0voF3g)(NimStringDesc* path);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkSymlink_KkZgXPy74tXi49bh8QSie8g)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringDesc* path);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosparentDir)(NimStringDesc* path);
extern int cmdCount;
extern NCSTRING* cmdLine;
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_2, "PATH", 4);
STRING_LITERAL(TM_yu6cxgKBBXbNsTkT9cyMd4g_3, "", 0);

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename) {
	NIM_BOOL result;
	struct stat res;
	NIM_BOOL T1_;
	int T2_;
{	result = (NIM_BOOL)0;
	memset((void*)(&res), 0, sizeof(res));
	T1_ = (NIM_BOOL)0;
	T2_ = (int)0;
	T2_ = stat(filename->data, (&res));
	T1_ = (((NI32) 0) <= T2_);
	if (!(T1_)) goto LA3_;
	T1_ = S_ISREG(res.st_mode);
	LA3_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, checkSymlink_KkZgXPy74tXi49bh8QSie8g)(NimStringDesc* path) {
	NIM_BOOL result;
	struct stat rawInfo;
	result = (NIM_BOOL)0;
	memset((void*)(&rawInfo), 0, sizeof(rawInfo));
	{
		int T3_;
		T3_ = (int)0;
		T3_ = lstat(path->data, (&rawInfo));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA4_: ;
	{
		result = S_ISLNK(rawInfo.st_mode);
	}
	LA1_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, findExe_XcLgn9booQ6akyBsF074Lfw)(NimStringDesc* exe, NIM_BOOL followSymlinks, NimStringDesc** extensions, NI extensionsLen_0) {
	NimStringDesc* result;
	NimStringDesc* path;
{	result = (NimStringDesc*)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = contains_6e5MGL10HDAJ205lBYpWxw(exe, 47);
		if (!T3_) goto LA4_;
		{
			NimStringDesc* ext;
			NI i;
			ext = (NimStringDesc*)0;
			i = ((NI) 0);
			{
				while (1) {
					if (!(i < extensionsLen_0)) goto LA8;
					ext = extensions[i];
					result = nosaddFileExt(exe, ext);
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = nosexistsFile(result);
						if (!T11_) goto LA12_;
						goto BeforeRet_;
					}
					LA12_: ;
					i += ((NI) 1);
				} LA8: ;
			}
		}
	}
	LA4_: ;
	path = getEnv_9b1nh9cAHhSLlHOPz8lCk5FA(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_2), ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
	{
		NimStringDesc* candidate;
		NI last;
		NI splits;
		candidate = (NimStringDesc*)0;
		last = ((NI) 0);
		splits = ((NI) -1);
		{
			while (1) {
				NI first;
				NimStringDesc* x;
				NimStringDesc* T25_;
				if (!(last <= (path ? path->Sup.len : 0))) goto LA16;
				first = last;
				{
					while (1) {
						NIM_BOOL T19_;
						T19_ = (NIM_BOOL)0;
						T19_ = (last < (path ? path->Sup.len : 0));
						if (!(T19_)) goto LA20_;
						T19_ = !(((NU8)(path->data[last]) == (NU8)(58)));
						LA20_: ;
						if (!T19_) goto LA18;
						last += ((NI) 1);
					} LA18: ;
				}
				{
					if (!(splits == ((NI) 0))) goto LA23_;
					last = (path ? path->Sup.len : 0);
				}
				LA23_: ;
				candidate = copyStrLast(path, first, (NI)(last - ((NI) 1)));
				T25_ = (NimStringDesc*)0;
				T25_ = expandTilde_DOCYVvghSr9cSjyIq0voF3g(candidate);
				x = slash__lXoMhn1ZYc9cAJa9bfA61msg(T25_, exe);
				{
					NimStringDesc* ext_2;
					NI i_2;
					ext_2 = (NimStringDesc*)0;
					i_2 = ((NI) 0);
					{
						while (1) {
							NimStringDesc* x_2;
							if (!(i_2 < extensionsLen_0)) goto LA28;
							ext_2 = extensions[i_2];
							x_2 = nosaddFileExt(x, ext_2);
							{
								NIM_BOOL T31_;
								T31_ = (NIM_BOOL)0;
								T31_ = nosexistsFile(x_2);
								if (!T31_) goto LA32_;
								{
									while (1) {
										if (!followSymlinks) goto LA35;
										{
											NIM_BOOL T38_;
											NimStringDesc* r;
											NI len;
											T38_ = (NIM_BOOL)0;
											T38_ = checkSymlink_KkZgXPy74tXi49bh8QSie8g(x_2);
											if (!T38_) goto LA39_;
											r = mnewString(((NI) 256));
											len = readlink(x_2->data, r->data, ((NI) 256));
											{
												NI32 T45_;
												if (!(len < ((NI) 0))) goto LA43_;
												T45_ = (NI32)0;
												T45_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
												raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T45_, ((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
											}
											LA43_: ;
											{
												if (!(((NI) 256) < len)) goto LA48_;
												r = mnewString(((NI) ((NI)(len + ((NI) 1)))));
												len = readlink(x_2->data, r->data, len);
											}
											LA48_: ;
											r = setLengthStr(r, ((NI) (len)));
											{
												NIM_BOOL T52_;
												T52_ = (NIM_BOOL)0;
												T52_ = nosisAbsolute(r);
												if (!T52_) goto LA53_;
												x_2 = copyString(r);
											}
											goto LA50_;
											LA53_: ;
											{
												NimStringDesc* T56_;
												T56_ = (NimStringDesc*)0;
												T56_ = nosparentDir(x_2);
												x_2 = slash__lXoMhn1ZYc9cAJa9bfA61msg(T56_, r);
											}
											LA50_: ;
										}
										goto LA36_;
										LA39_: ;
										{
											goto LA34;
										}
										LA36_: ;
									} LA35: ;
								} LA34: ;
								result = copyString(x_2);
								goto BeforeRet_;
							}
							LA32_: ;
							i_2 += ((NI) 1);
						} LA28: ;
					}
				}
				{
					if (!(splits == ((NI) 0))) goto LA60_;
					goto LA15;
				}
				LA60_: ;
				splits -= ((NI) 1);
				last += ((NI) 1);
			} LA16: ;
		} LA15: ;
	}
	result = copyString(((NimStringDesc*) &TM_yu6cxgKBBXbNsTkT9cyMd4g_3));
	}BeforeRet_: ;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void) {
}

