/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection -O3 -fno-strict-aliasing  -I/usr/share/nim -o /home/kavis/Documents/Project/ETC/New_Music/nimcache/stdlib_strutils.o /home/kavis/Documents/Project/ETC/New_Music/nimcache/stdlib_strutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_UV3llMMYFckfui8YMBuUZA tyTuple_UV3llMMYFckfui8YMBuUZA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyTuple_UV3llMMYFckfui8YMBuUZA {
NimStringDesc* Field0;
NimStringDesc* Field1;
};
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuContinuesWith)(NimStringDesc* s, NimStringDesc* substr, NI start);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_JGc9b9bh2D3nTdUR7TGyq8aA_2 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuContinuesWith)(NimStringDesc* s, NimStringDesc* substr, NI start) {
	NIM_BOOL result;
	NI i;
{	result = (NIM_BOOL)0;
	i = ((NI) 0);
	{
		while (1) {
			{
				if (!((NU8)(substr->data[i]) == (NU8)(0))) goto LA5_;
				result = NIM_TRUE;
				goto BeforeRet_;
			}
			LA5_: ;
			{
				if (!!(((NU8)(s->data[(NI)(i + ((NI) (start)))]) == (NU8)(substr->data[i])))) goto LA9_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
			LA9_: ;
			i += ((NI) 1);
		}
	}
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, multiReplace_umfhYZ3JuLdIcd167CziMw)(NimStringDesc* s, tyTuple_UV3llMMYFckfui8YMBuUZA* replacements, NI replacementsLen_0) {
	NimStringDesc* result;
	NI i;
	tySet_tyChar_nmiMWKVIe46vacnhAFrQvw fastChk;
	result = (NimStringDesc*)0;
	result = rawNewString(((NI) ((s ? s->Sup.len : 0))));
	i = ((NI) 0);
	memset((void*)fastChk, 0, sizeof(fastChk));
	memcpy((void*)fastChk, (NIM_CONST void*)TM_JGc9b9bh2D3nTdUR7TGyq8aA_2, 32);
	{
		tyTuple_UV3llMMYFckfui8YMBuUZA tup;
		NI i_2;
		memset((void*)(&tup), 0, sizeof(tup));
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < replacementsLen_0)) goto LA3;
				tup.Field0 = replacements[i_2].Field0;
				tup.Field1 = replacements[i_2].Field1;
				fastChk[(NU)(((NU8)(tup.Field0->data[((NI) 0)])))>>3] |=(1U<<(((NU8)(tup.Field0->data[((NI) 0)]))&7U));
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	{
		while (1) {
			if (!(i < (s ? s->Sup.len : 0))) goto LA5;
			{
				{
					if (!((fastChk[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0)) goto LA9_;
					{
						tyTuple_UV3llMMYFckfui8YMBuUZA tup_2;
						NI i_3;
						memset((void*)(&tup_2), 0, sizeof(tup_2));
						i_3 = ((NI) 0);
						{
							while (1) {
								if (!(i_3 < replacementsLen_0)) goto LA13;
								tup_2.Field0 = replacements[i_3].Field0;
								tup_2.Field1 = replacements[i_3].Field1;
								{
									NIM_BOOL T16_;
									T16_ = (NIM_BOOL)0;
									T16_ = nsuContinuesWith(s, tup_2.Field0, ((NI) (i)));
									if (!T16_) goto LA17_;
									result = resizeString(result, tup_2.Field1->Sup.len + 0);
appendString(result, tup_2.Field1);
									i += (tup_2.Field0 ? tup_2.Field0->Sup.len : 0);
									goto LA6;
								}
								LA17_: ;
								i_3 += ((NI) 1);
							} LA13: ;
						}
					}
				}
				LA9_: ;
				result = addChar(result, s->data[i]);
				i += ((NI) 1);
			} LA6: ;
		} LA5: ;
	}
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

